-- Palm Pizza Kitchen MySQL schema
CREATE DATABASE IF NOT EXISTS palm_pizza CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE palm_pizza;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('customer', 'admin') NOT NULL DEFAULT 'customer',
  phone VARCHAR(40) NULL,
  email_verified TINYINT(1) NOT NULL DEFAULT 0,
  verify_code VARCHAR(10) NULL,
  verify_token VARCHAR(64) NULL,
  verify_expires_at DATETIME NULL,
  reset_code VARCHAR(10) NULL,
  reset_token VARCHAR(64) NULL,
  reset_expires_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS menu_items (
  id VARCHAR(80) PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  image VARCHAR(500) NOT NULL,
  rating DECIMAL(3,1) NOT NULL DEFAULT 5.0,
  reviews INT UNSIGNED NOT NULL DEFAULT 0,
  badge VARCHAR(40) NULL,
  category ENUM('classic','cheese','veggie','meat','side','combo','drink','burger') NOT NULL,
  details LONGTEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS menu_images (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id VARCHAR(80) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (item_id) REFERENCES menu_items(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS offers (
  id VARCHAR(40) PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  code VARCHAR(40) NOT NULL UNIQUE,
  status ENUM('Active','Scheduled','Paused') NOT NULL DEFAULT 'Active',
  ends_on VARCHAR(80) NOT NULL,
  description TEXT NULL,
  deal_label VARCHAR(120) NULL,
  terms TEXT NULL,
  href VARCHAR(200) NULL,
  image_url VARCHAR(500) NULL,
  show_on_home TINYINT(1) NOT NULL DEFAULT 1,
  menu_item_id VARCHAR(40) NULL,
  size_prices TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(40) PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  customer_name VARCHAR(120) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  address TEXT NOT NULL,
  payment_method VARCHAR(40) NOT NULL DEFAULT 'card',
  status ENUM('Pending','Preparing','Out for delivery','Delivered','Cancelled') NOT NULL DEFAULT 'Pending',
  payment_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  customer_email VARCHAR(190) NULL,
  paid_at DATETIME NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  delivery_fee DECIMAL(12,2) NOT NULL DEFAULT 1500,
  total DECIMAL(10,2) NOT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id VARCHAR(40) NOT NULL,
  item_id VARCHAR(80) NULL,
  name VARCHAR(160) NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES menu_items(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cart_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  item_id VARCHAR(80) NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_item (user_id, item_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES menu_items(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS settings (
  setting_key VARCHAR(80) PRIMARY KEY,
  setting_value TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contact_messages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS payment_transactions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id VARCHAR(40) NOT NULL,
  customer_reference VARCHAR(80) NOT NULL UNIQUE,
  gateway_refid VARCHAR(80) NULL,
  gateway_tid VARCHAR(80) NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'RWF',
  pmethod VARCHAR(16) NOT NULL DEFAULT 'momo',
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  payment_url TEXT NULL,
  gateway_payload LONGTEXT NULL,
  receipt_sent TINYINT(1) NOT NULL DEFAULT 0,
  owner_notified TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS payouts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_reference VARCHAR(80) NOT NULL UNIQUE,
  internal_ref VARCHAR(80) NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'RWF',
  recipient_name VARCHAR(120) NOT NULL,
  msisdn VARCHAR(20) NOT NULL,
  telecom_provider_id VARCHAR(20) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  status_message TEXT NULL,
  initiated_by INT UNSIGNED NULL,
  gateway_payload LONGTEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  idempotency_key VARCHAR(190) PRIMARY KEY,
  event_type VARCHAR(80) NOT NULL DEFAULT '',
  processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
